### ISSUE TITLE
How to port freertos-cell to arm64

### ISSUE THREAD

**Issue by hitmoon** [siemens/freertos-cell#3]
@johann-pfefferl 
I want to port the freertos-cell to arm64 platform board (jetson tx2), But I don't know how to start. 

Should I  modify pieces under freertos-runtime directory and add arm64 support ?  Besides, I think it's better to let the UART working and print something.

I Googled for a while and it seems no one has port to arm64 before.
Can you give me a hint where should I start or what to reference ?
Thanks!

**Comment by johann-pfefferl** [comment]
Hello,

you must create a platform specific "porting" part under the directory

freertos/Source/portable/GCC/ARM64_jailhouse

The 32 Bit porting code can be found under

freertos/Source/portable/GCC/ARM_A7jailhouse

for the BananaPi board. Find a port in the freertos sources for a 64bit
platform and adapt it to your board.

Next you have to modify the bootstrapping code of the platform which can
be found in the

boot_stub.S

assembler file. There you have to setup the stacks for interrupt and
normal runtime context.

In the file "main.c" you must adjust the MMU and Caching setup. If you
don't want to use MMU and Caching you can leave this out. But I
recommend to use it mainly due to performance reasons.

Of course you also have to adapt the serial line code to the one of the
tegra platform.

Hans

hitmoon <notifications@github.com> wrote:
> @johann-pfefferl 
> I want to port the freertos-cell to arm64 platform board (jetson tx2), But I don't know how to start. 
> 
> Should I  modify pieces under freertos-runtime directory and add arm64 support ?  Besides, I think it's better to let the UART working and print something.
> 
> I Googled for a while and it seems no one has port to arm64 before.
> Can you give me a hint where should I start or what to reference ?
> Thanks! 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/siemens/freertos-cell/issues/3

-- 
Siemens AG
Corporate Technology
Research & Technology Center
CT RDA IOT SES-DE
Otto-Hahn-Ring 6
81739 Muenchen, Germany
mailto: johann.pfefferl@siemens.com
phone: +49 1520 3450 138
fax:   +49 89 636 33045
_____________________________________________________
SIEMENS AG: Chairman of the Supervisory Board: Jim Hagemann Snabe
Managing Board: Joe Kaeser, Chairman, President and Chief Executive Officer
Roland Busch, Lisa Davis, Klaus Helmrich, Janina Kugel, Cedrik Neike,
Michael Sen, Ralf P. Thomas
Registered offices: Berlin and Munich, Germany
Commercial registries: Berlin Charlottenburg, HRB 12300, Munich, HRB 6684
WEEE-Reg.-No. DE 23691322

**Comment by hitmoon** [comment]
@johann-pfefferl 
 I will give a try.
 Thank you!
